"""init

Revision ID: 275d497f6b4a
Revises: 
Create Date: 2026-07-05 13:13:10.387946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '275d497f6b4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS hh")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hh'
    )
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accredited_it_employer', sa.Boolean(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    schema='hh'
    )
    op.create_table('hh_parse_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('per_page', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hh'
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='hh'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='hh'
    )
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_from', sa.Integer(), nullable=True),
    sa.Column('s_to', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=2048), nullable=True),
    sa.Column('gross', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hh'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='hh'
    )
    op.create_table('role_permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['hh.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['hh.role.id'], ),
    sa.PrimaryKeyConstraint('permission_id', 'role_id'),
    schema='hh'
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['hh.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['hh.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='hh'
    )
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('publishied_at', sa.String(length=2048), nullable=False),
    sa.Column('requirement', sa.String(length=2048), nullable=True),
    sa.Column('responsobility', sa.String(length=2048), nullable=True),
    sa.Column('schedule', sa.String(length=2048), nullable=False),
    sa.Column('prof_roles', sa.String(length=2048), nullable=False),
    sa.Column('exp', sa.String(length=2048), nullable=False),
    sa.Column('empoyment', sa.String(length=2048), nullable=False),
    sa.Column('employers_name', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['hh.area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hh'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SCHEMA IF EXISTS hh CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('vacancy', schema='hh')
    op.drop_table('user_role', schema='hh')
    op.drop_table('role_permission', schema='hh')
    op.drop_table('user', schema='hh')
    op.drop_table('salary', schema='hh')
    op.drop_table('role', schema='hh')
    op.drop_table('permission', schema='hh')
    op.drop_table('hh_parse_state', schema='hh')
    op.drop_table('employer', schema='hh')
    op.drop_table('area', schema='hh')
    # ### end Alembic commands ###
