"""starter data

Revision ID: 6672b11be659
Revises: 9fc27f79eb2e
Create Date: 2026-03-02 01:20:17.156817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6672b11be659'
down_revision: Union[str, Sequence[str], None] = '9fc27f79eb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO role (id, name) VALUES
        (1, 'user'),
        (2, 'moderator'),
        (3, 'admin')
        ON CONFLICT (id) DO NOTHING;
    """)

    # права
    op.execute("""
        INSERT INTO permission (id, name) VALUES
        (1, 'view_vacancy'),
        (2, 'update_db'),
        (3, 'ban_user'),
        (4, 'view_users')
        ON CONFLICT (id) DO NOTHING;
    """)

    # связь роли и прав
    op.execute("""
        INSERT INTO role_permission (role_id, permission_id) VALUES
        (1, 1),                -- user: view_vacancy
        (2, 1), (2, 4),        -- moderator
        (3, 1), (3, 2), (3, 3), (3, 4)  -- admin
        ON CONFLICT DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
