"""Rework ORM models

Revision ID: df3aec9504b6
Revises: 275d497f6b4a
Create Date: 2026-07-06 17:16:33.220099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3aec9504b6'
down_revision: Union[str, Sequence[str], None] = '275d497f6b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('vacancy_id', sa.Integer(), nullable=True), schema='hh')
    op.execute("UPDATE hh.salary SET vacancy_id=id")
    op.alter_column('salary', 'vacancy_id', nullable=False, schema='hh')
    op.create_foreign_key(None, 'salary', 'vacancy', ['vacancy_id'], ['id'], source_schema='hh', referent_schema='hh', ondelete='CASCADE')

    op.execute("CREATE SEQUENCE IF NOT EXISTS hh.salary_id_seq")
    op.execute("UPDATE hh.salary SET id = nextval('hh.salary_id_seq')")
    op.execute("ALTER TABLE hh.salary ALTER COLUMN id SET DEFAULT nextval('hh.salary_id_seq')")
    op.execute("SELECT setval('hh.salary_id_seq', (SELECT max(id) FROM hh.salary))")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE hh.salary ALTER COLUMN id DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS hh.salary_id_seq")
    op.drop_constraint('uq_salary_vacancy', 'salary', type_='unique', schema='hh')
    op.drop_constraint('fk_salary_vacancy', 'salary', type_='foreignkey', schema='hh')
    op.drop_column('salary', 'vacancy_id', schema='hh')
    # ### end Alembic commands ###
